Feat/yandex map
VentionCapstone/FrontEnd pull request #17
Opened 2023-12-28 21:04 UTC by Sinumi

I cloned this branch from accommodation crud which is not merged yet so it's still showing a lot files but the only files that change/added are "YandexMap.tsx" and "AccommodationForm.tsx"

2023-12-29 10:58 UTC, gitkoshelew requested changes

2023-12-29 10:58 UTC, gitkoshelew commented on src/pages/accommodations/AccommodationForm.tsx
> +    if (id) {
please make it flat
if (!id) {
   createAccommodation
  return
}
if (!Object.keys(dirtyFields).length) {
...
return
}
updateAccommodation....

2023-12-29 10:58 UTC, gitkoshelew commented on src/pages/accommodations/AccommodationForm.tsx
> +    setValue('address.latitude', coords[0], {
please use spread const handleCoordsChange = ([lat, long]: [number, number])

2023-12-29 10:58 UTC, gitkoshelew commented on src/pages/accommodations/AccommodationForm.tsx
> +      <form onSubmit={(e) => void handleSubmit(onSubmit)(e)}>
check skype chat wednesday 8.27 pm

2023-12-29 10:58 UTC, gitkoshelew commented on src/pages/accommodations/AccommodationForm.tsx
> +                  format="MM-DD-YYYY"
there is constant for format in our project

2023-12-29 10:58 UTC, gitkoshelew commented on src/pages/accommodations/AccommodationForm.tsx
> +                  format="MM-DD-YYYY"
the same

2023-12-29 10:58 UTC, gitkoshelew commented on src/pages/accommodations/AccommodationForm.tsx
> +                onChange={(e) => field.onChange(Number(e.target.value))}
see previous comment

2023-12-29 10:58 UTC, gitkoshelew commented on src/pages/accommodations/AccommodationForm.tsx
> +            <Button variant="outlined" onClick={() => navigate(ROUTES.accommodations.root)}>
create special function navigateToRoot

2023-12-29 10:58 UTC, gitkoshelew commented on src/pages/accommodations/AccommodationForm.tsx
> +            render={({ field }) => (
create memoized functions for each render. like renderTitle = useMemo((field)=>{
                <TextField
                {...field}
                label="Title"
                error={!!errors.title}
                helperText={errors.title?.message}
              />
}, [errors]

2023-12-29 10:58 UTC, gitkoshelew commented on src/pages/accommodations/index.tsx
> +          : accommodations?.data.data.slice(0, 10).map((accommodation) => (
use spread here. .map(({id, previewImgUrl....})

2023-12-29 10:58 UTC, gitkoshelew commented on tsconfig.json
> +      "@/*": ["src/*"]
very useful improvement, thanks

2024-01-10 20:04 UTC, gitkoshelew commented on src/api/queries/accommodations/useGetAccommodation.ts
> +      }>(ENDPOINTS.accommodation.getAccommodation(id || ''));
don't think that you need the condition (id || ''). looks like exception. Doesn't 'enabled' option cover this case?

2024-01-10 20:04 UTC, gitkoshelew commented on src/api/queries/account/useGetUserQuery.ts
>  function useGetUserQuery(userId: string | null, isLoggedIn: boolean) {
you should be sure on the component level that userId is string and use strict type, or handle the error somehow

2024-01-10 20:04 UTC, gitkoshelew commented on src/api/queries/account/useGetUserQuery.ts
>  function useGetUserQuery(userId: string | null, isLoggedIn: boolean) {
and then you don't need 'as string' transformation below

2024-01-10 20:04 UTC, gitkoshelew commented on src/components/YandexMap.tsx
> +  setCoords?: ([latitude, longitude]: number[]) => void;
I think we need the tuple Coordinates [latitude, longitude] for our project, looks like it will be frequently used [latitude, longitude]

2024-01-10 20:04 UTC, gitkoshelew commented on src/components/navigation/TopNavMenu.tsx
> +                key="signIn"
the same key as from previous link. Use value from 'to' property. Looks like it's unique

2024-01-10 20:04 UTC, gitkoshelew commented on src/constants/index.ts
> +export const DATE_FORMAT = 'MM-DD-YYYY';
)) finally we have the constant. thank you

2024-01-10 20:04 UTC, gitkoshelew commented on src/pages/accommodations/AccommodationForm.tsx
> +            label="Title"
wasn't i18n pr merged yet. If not, notify teammate who working on it after merge that you have new CTAs

2024-01-10 20:04 UTC, gitkoshelew commented on src/pages/accommodations/AccommodationForm.tsx
> +            <Button type="submit" variant="contained">
looks like we need type for 'variant' or Button already contains this field type?

2024-01-10 20:04 UTC, gitkoshelew commented on src/pages/accommodations/index.tsx
> +          : accommodations?.data.data
extract, please data.data inside useGetAccommodations to not write it every time

2024-01-10 20:04 UTC, gitkoshelew commented on src/pages/accommodations/index.tsx
> +          ? Array.from({ length: 10 }).map((_, i) => (
create component for the Skeleton view. looks like it useful for many components

2024-01-10 20:05 UTC, gitkoshelew approved these changes

2024-01-10 23:21 UTC, Sinumi commented on src/pages/accommodations/AccommodationForm.tsx
> +            label="Title"
Not yet, I'll notify team

2024-01-10 23:22 UTC, Sinumi commented on src/pages/accommodations/AccommodationForm.tsx
> +            <Button type="submit" variant="contained">
no needed, Button is comming from MUI so it has already own types for variant

2024-01-10 23:37 UTC, merged