Fix/yandex map
VentionCapstone/FrontEnd pull request #44
Opened 2024-01-30 12:46 UTC by fasbrothers

2024-01-30 19:00 UTC, adadychanka requested changes

2024-01-30 19:00 UTC, adadychanka commented on src/api/queries/accommodation/useGetLocationSuggestions.ts
> +function useGetLocationSuggestions(value: string) {
`searchValue` is a bit nicer

2024-01-30 19:00 UTC, adadychanka commented on src/api/queries/accommodation/useGetLocationSuggestions.ts
> +    enabled: value.length > 2,
Magic number, pls, create a constant for this

2024-01-30 19:00 UTC, adadychanka commented on src/api/queries/accommodation/useGetSelectedAddress.ts
> +function useGetSelectedAddress(value: [number, number]) {
Create a type for the lat lng representation

2024-01-30 19:00 UTC, adadychanka commented on src/api/queries/accommodation/useGetSelectedAddress.ts
> +    enabled: value[0] !== 0 && value[1] !== 0,
use array destruction here to make more readable code

`const [lat, lng] = value`

2024-01-30 19:00 UTC, adadychanka commented on src/api/queries/accommodation/useGetSelectedAddress.ts
> +      return data.response.GeoObjectCollection.featureMember[0].GeoObject;
What do you think about putting optional chaining here?

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/MapView.tsx
> +const MapView = ({ address, setAddress, handleCoordsChange, addressWatch }: MapViewType) => {
when you pass callbacks to component, they should be named starting with `on`

`onCoordsChange`

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/MapView.tsx
> +const MapView = ({ address, setAddress, handleCoordsChange, addressWatch }: MapViewType) => {
Usually type of props has a name `{COMPONENT_NAME}Props`

`MapViewProps`

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/MapView.tsx
> +      void map.current.setCenter(coords, 15, {});
Magic number `15`

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/MapView.tsx
> +        apikey: import.meta.env.VITE_YANDEX_API_KEY as string,
It can be moved to constants and be used from there

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/MapView.tsx
> +        apikey: import.meta.env.VITE_YANDEX_API_KEY as string,
The whole map query can be moved out to constants even

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/MapView.tsx
> +          zoom: 15,
to constants pls

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/MapView.tsx
> +          center: checkCoordinates()
why do you need `checkCoordinates` as a function? It can be just value

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/MapView.tsx
> +            balloonContent: address ? address.name : 'Select location',
Should "Select location" be translated?

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/MapView.tsx
> +export default MapView;
it think `memo` is useful here

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/MapView.tsx
> +            ? [addressWatch.latitude, addressWatch.longitude]
can be extracted to variable in function body + wrapped in `useMemo`

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/SearchLocation.tsx
> +  handleCoordsChange,
on

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/SearchLocation.tsx
> +  handleAddressChange,
on

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/SearchLocation.tsx
> +    if (data && data.response.GeoObjectCollection.featureMember.length > 0) {
if you have this long access to the property you need, you can create a selector function to use the unified way of accessing fields from responce

something like `selectGeoSearchFeaturedObjects`
```ts
function selectGeoSearchFeaturedObjects(searchResponce: SuggestionsResponse) {
  return searchResponce?.response?.GeoObjectCollection?.featureMember ?? [];
}
```

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/SearchLocation.tsx
> +    const pageClickEvent = (e: MouseEvent) => {
`EventHandler` because it's a handler

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/SearchLocation.tsx
> +      handleCoordsChange(stringToNumberOfArray(item.Point.pos) as [number, number]);
you don't need type casting here

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/SearchLocation.tsx
> +          Location: {addressWatch.country}, {addressWatch.city}, {addressWatch?.street}
Should it be translated?

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/SearchLocation.tsx
> +        placeholder="Search location"
translation?

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/SearchLocation.tsx
> +          Selected location:{' '}
translation?

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/SearchLocation.tsx
> +          {address.metaDataProperty.GeocoderMetaData.AddressDetails.Country.AddressLine}
for the future, I think it's worth creating a class wrapper for this to have more convenient access to needed data

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/SearchResults.tsx
> +  handleItemClick: (item: GeoObject) => void;
on

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/SearchResults.tsx
> +              component={'div'}
it's `div` by default, isn't it?

2024-01-30 19:00 UTC, adadychanka commented on src/components/shared/YandexMap.tsx
> +          center: [latitude || DEFAULT_LATITUDE, longitude || DEFAULT_LONGITUDE],
repetitive code, can be extracted to the body of function

2024-01-30 19:00 UTC, adadychanka commented on src/config/endpoints.config.ts
> +const BASE_YANDEX_URL = import.meta.env.VITE_YANDEX_SUGGEST_API_URL as string;
all env variables should be stored in a separate file and be taken from that file

2024-01-30 19:00 UTC, adadychanka commented on src/constants/index.ts
> +export const DEFAULT_COORDINATES = [DEFAULT_LATITUDE, DEFAULT_LONGITUDE];
`as const` can help to narrow type from `number[]` to `[number, number]`

2024-01-30 19:00 UTC, adadychanka commented on src/pages/accommodations/components/AccommodationForm.tsx
>    const isDeleted: boolean = !!accommodation?.isDeleted;
`!!` casts type to a boolean

2024-01-30 19:00 UTC, adadychanka commented on src/pages/accommodations/components/FormFields.tsx
> +  handleCoordsChange: (coords: [number, number]) => void;
on

2024-01-30 19:00 UTC, adadychanka commented on src/types/accommodation.types.ts
> +    .min(5, 'Title must be at least 5 characters')
I think these validation messages should be translated as well

2024-01-30 19:00 UTC, adadychanka commented on src/utils/index.ts
> +  return [Number.parseFloat(splitted[1]), Number.parseFloat(splitted[0])];
I think it would be nice to have `NaN` case here

2024-01-31 11:17 UTC, fasbrothers commented on src/constants/index.ts
> +export const DEFAULT_COORDINATES = [DEFAULT_LATITUDE, DEFAULT_LONGITUDE];
![image](https://github.com/VentionCapstone/FrontEnd/assets/60430639/d0f73c77-aa0e-4d11-b935-e6613d91f4a1)
I could not add as const, it shows an error

2024-01-31 16:29 UTC, adadychanka approved these changes

2024-01-31 16:29 UTC, adadychanka commented on src/api/queries/accommodation/useGetSelectedAddress.ts
> +      return data?.response?.GeoObjectCollection?.featureMember[0]?.GeoObject;
You can apply `selectGeoSearchFeaturedObjects` here as well

2024-01-31 16:29 UTC, adadychanka commented on src/components/shared/MapView.tsx
> +    return [addressWatch.latitude, addressWatch.longitude];
```suggestion
    return (addressWatch.latitude !== 0 && addressWatch.longitude !== 0) ? [addressWatch.latitude, addressWatch.longitude] : DEFAULT_COORDINATES;
```

2024-01-31 16:29 UTC, adadychanka commented on src/components/shared/MapView.tsx
> +export default MemoMapView;
```suggestion
export default memo(MemoMapView);
```

2024-01-31 16:29 UTC, adadychanka commented on src/config/endpoints.config.ts
> +    getSelectedLocation: (value: [number, number]) =>
`value` => `coordinates`

2024-01-31 16:29 UTC, adadychanka commented on src/constants/index.ts
> +export const DEFAULT_COORDINATES = [DEFAULT_LATITUDE, DEFAULT_LONGITUDE];
```suggestion
export const DEFAULT_COORDINATES: [number, number] = [DEFAULT_LATITUDE, DEFAULT_LONGITUDE];
```

Should work

2024-01-31 17:54 UTC, merged