Feature/23 email validation
VentionCapstone/FrontEnd pull request #8
Opened 2023-12-13 15:30 UTC by fasbrothers

2023-12-13 17:52 UTC, mirsadikov approved these changes

2023-12-14 08:54 UTC, otabek requested changes

2023-12-14 08:54 UTC, otabek commented on src/api/mutations/auth/useVerifyEmailMutation.ts
> +      navigate('/auth/signin');
can you also add this route to src/api/routes.ts

2023-12-14 08:54 UTC, otabek commented on src/api/routes.ts
> +export const VERIFY_EMAIL_ROUTE = '/auth/verify';
better to separate if more than one route 

```
export const AUTH_ROUTE = '/auth';
export const VERIFY_EMAIL_ROUTE = `${AUTH_ROUTE}/verify`;
```

2023-12-14 08:54 UTC, otabek commented on src/pages/auth/VerifyEmail.tsx
> +  const { isPending, mutate } = useVerifyEmailMutation(token);
what happens if it fails to verify the email?

2023-12-15 11:11 UTC, otabek requested changes

2023-12-15 11:11 UTC, otabek commented on src/components/mainNavigationStyles.ts
stick to one file naming convention and create folder for each component 
```
components/navigation/MainNavigation.tsx
components/navigation/MainNavigation.styles.ts
```

2023-12-15 11:47 UTC, MdRasulov approved these changes

2023-12-15 12:55 UTC, otabek approved these changes

2023-12-15 12:58 UTC, merged